# Generated by Django 3.1.4 on 2020-12-14 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postheader', models.CharField(max_length=100)),
                ('postcontent', models.TextField()),
                ('postdate', models.DateField(auto_now_add=True)),
                ('postauthor', models.CharField(max_length=50)),
                ('postimage', models.TextField()),
            ],
        ),
    ]
